config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
    path('projects/',include('projects.urls')),
    path('',include('main.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<str:category_name>/category',views.CategoryView.as_view(),name='category')
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('new/',views.new_project,name='new'),
    path('<int:project_id>/detail',views.project_detail,name='detail')
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('profile/<str:username>/',views.ProfileView.as_view(),name='profile'),
    path('update/',views.UpdateProfileView.as_view(),name='update')
]

main/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name
    
class Project(models.Model):
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='project_images')
    file = models.FileField(upload_to='project_file')
    
    def __str__(self):
        return self.title
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=122)
    tg_username = models.CharField(max_length=150)
    avatar = models.ImageField(upload_to='avatars',default='avatars/default.png')
    
    def __str__(self):
        return self.username

projects/forms.py
from django import forms
from .models import Project

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title','description','category','file','image']
        
    def save(self,request,commit=True):
        project = self.instance
        project.author = request.user
        super().save(commit)
        return project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'category')
        

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser

class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name','last_name','username','email')
        
        
class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name','last_name','username','email','tg_username','phone_number','avatar']

main/views.py
from django.shortcuts import render,get_object_or_404
from django.views import View
from projects.models import Project,Category

# Create your views here.



class IndexView(View):
    def get(self,request):
        projects = Project.objects.all()
        q = request.GET.get('q','')
        if q:
            projects = projects.filter(title__icontains=q)
        return render(request,'index.html',{'projects':projects})
    
    
class CategoryView(View):
    def get(self,request,category_name):
        category = get_object_or_404(Category,name=category_name)
        projects = Project.objects.filter(category=category)
        q = request.GET.get('q','')
        if q:
            projects = projects.filter(title__icontains=q)
        return render(request,'category.html',{'projects':projects,'category':category})
    
    
def for_all_pages(request):
    categories = Category.objects.all()
    

projects/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import NewProjectForm,ProjectForm
from django.contrib.auth.decorators import login_required
from .models import Project,Category
from django.http import HttpResponse
from django.contrib import messages

# Create your views here.

def new_project(request):
    if request.method == 'GET':
        form = NewProjectForm()
        context = {
            'form':form
        }
        return render(request,'new_project.html',context)
    elif request.method == 'POST':
        form = NewProjectForm(request.POST,files=request.FILES)
        if form.is_valid():
            form.save(request=request)
            messages.success(request,'Succesfully Created')
            return redirect('main:index')
        return render(request,'new_project.html',{'form':form})

def project_detail(request,project_id):
    project = get_object_or_404(Project,id=project_id)
    context = {
        'project':project
    }
    return render(request,'project_detail.html',context)
    
            

users/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.mixins import UserPassesTestMixin,LoginRequiredMixin
from django.views import View
from .forms import SignUpForm
from django.contrib import messages
from .models import CustomUser
# Create your views here.

class SignUpView(UserPassesTestMixin,View):
    
    def get(self,request):
        context = {
            'form':SignUpForm()
        }
        return render(request,'registration/signup.html',context)
    
    def post(self,request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Your account is succesfully created.')
            return redirect('login')
        return render(request,'registration/signup.html',{'form':form})
        
    def test_func(self):
        user = self.request.user
        if user.is_authenticated:
            return False
        return True
    
class ProfileView(View):
    def get(self,request,username):
        user = get_object_or_404(CustomUser,username=username)
        context = {
            'customuser':user
        }
        return render(request,'profile.html',context)


class UpdateProfileView(LoginRequiredMixin,View):
    login_url = 'login'
    
    def get(self,request):
        form = UpdateProfileView(request.user)
        context = {
            'form':form
        }
        return render(request,'update_profile.html',context)
    
    def post(self,request):
        form = UpdateProfileView(instance=request.user,data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account is successfully updated.')
            return redirect('profile',request.user)
        return render(request,'registration/signup.html',{'form':form})
            

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F4B41A;">
        <div class="container">
          <a class="navbar-brand" href="/">All Projects</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-tem">
                <div class="btn-group">
                  <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    Categoriya
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                        {% for i in categories %}
                        <li><a class="dropdown-item" href="{% url 'main:category' i.name %}">{{i.title}}</a></li>
                        {% endfor %}
                  </ul>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'projects:new' %}">Loyiha qo'shish</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/">Saqlanganlar</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/">Oxirgilar</a>
              </li>
              
            </ul>
              <div class="btn-group">
                <form class="d-flex " role="search">
                  <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Izlash</button>
                </form>
                {% if request.user.is_authenticated %}
                <button type="button" class="btn  dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                  <img src="{{ request.user.avatar.url }}" width="35" height="35" class=" rounded" alt="">
                </button>
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg">
                  <li><a class="dropdown-item" href="{% url 'profile' request.user %}">Profile</a></li>
                  <li><a class="dropdown-item" href="/">Parolni almashtirish</a></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Chiqib ketish</a></li>
                </ul>
                <ul>
                    <a href="{% url 'logout' %}" class="btn btn-primary">Chiqib ketish</a>
                </ul>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-primary ms-auto">Saytga kirish</a>
                <a href="{% url 'signup' %}" class="btn btn-primary">Ro'yhatdan o'tish</a>
                {% endif %}
              </div>
          </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/category.html
{% extends "base.html" %}
{% block title %}
  E-Bazar - Home
{% endblock title %}

{% block content %}
   <!-- Product Cart Start -->
   <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products</h4>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in projects %}
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.project_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.description}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <a href="/">📥</a>
                        <a href="{% url 'products:detail' i.id %}" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            {% endfor %}          
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}
   <div class="container">
    <div class=" w-100 mt-4">
        <div class="row">
            <h4 class="d-block">Bu yerda o'rganishingiz uchun qilingan loyihalarni topishingiz mumkin</h4>
        </div>
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in projects %}
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                <img height="200" class=" card-img-top" src="{{i.image.url}}" alt="">
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <a href="/">🗳️</a>
                        <a href="{% url 'projects:detail' i.id %}" class="btn btn-outline-primary" >Ko'rish</a>
                    </div>
                </div>
            </div>  
            {% endfor %}
            
        </div>
    </div>
</div>
{% endblock content %}

templates/new_project.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
  E-bazar - New-Product
{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-6 mt-5 ">
            <h2>New Product</h2>
            <form  method="post" enctype="multipart/form-data">{% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary" >Submit</button>
                <a href="{% url 'main:index' %}" class="btn btn-secondary">Back</a>
            </form>
        </div>
        <div class="col"></div>
    </div>
  </div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 card mt-5 ">
            <div class="row">
                <div class="col-2 m-3">
                    <img class="img-thumbnail" width="150" height="150" src="{{customuser.avatar.url}}" alt="profile image">
                </div>
                <div class="col-8 m-3">
                    <h2>{{customuser.get_full_name}}</h2>
                    <p class="text-muted" >@{{customuser.username}} | {{customuser.email}}</p>
                    <!-- {% if customuser == request.user %}
                    <a class="btn btn-warning" href="{% url 'users:update' %}">Edit details</a>
                    <a class="btn btn-danger" href="{% url 'password_change' %}">Update Password</a>
                    {% endif %} -->
                    <a class="btn btn-primary" href="mailto:{{customuser.email}}">Email</a>
                    <!-- <a class="btn btn-primary" href="tel:{{customuser.phone_number}}">Call</a>
                    <a class="btn btn-primary" href="http://t.me/@{{customuser.tg_username}}">Telegram</a> -->
                </div>
            </div>
        </div>
    </div>
</div>  

 <div class="container">
    <div class=" w-100 mt-4">
        <h4 class="d-block" >Recently Products of @{{customuser}}</h4>
        {% if not customuser.project_set.exists %}
            <center class="text-muted" >There is no products</center>
        {% endif %}    
        <div class="d-flex flex-wrap justify-content-between">
            {% for i in customuser.project_set.all %}
    
            <div class="card border border-0 shadow-sm d-inline-block m-1 mt-3" style="width: 16.5rem;" >
                {% if i.project_set.exists %}
                <img height="200" class=" card-img-top" src="{{i.project_set.image.url}}" alt="">
                {% else %}
                <img height="200" class=" card-img-top" src="images/14pro2.jfif" alt="">
                {% endif %}
                <div class="card-body">
                    <h6 class="align-center card-title">{{i.title}}</h6>
                    <span class="center card-text"><small>$ {{i.description}}</small></span>
                    <div class="buttons d-flex flex-wrap justify-content-between ">
                        <i class="bi bi-bookmark-fill"></i> 
                        <a href="#" class="btn btn-outline-primary" >Details</a>
                    </div>
                </div>
            </div>  
            {% endfor %}
            
        </div>
    </div>
</div> 

{% endblock content %}

templates/project_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <h4><strong>{{project.title}}</strong></h4>
            <h5>{{project.description}}</h5>
            <h5>Muallif:{{project.author}}</h5>
            <img src="{{project.image.url}}" width="200" height="200" >
            {% if project.file %}
            <p>Download: <a href="{{ project.file.url }}">{{project.title}}📩</a></p>
            {% endif %}
        </div>
        <div class="col-4"></div>
    </div>
</div>

{% endblock content %}